# Will create a Standard AnythingLLM docker container
# with a 10GB storage disk mounted to /storage
# See Standard compute tier  pricing costs: https://render.com/pricing
# Standard tier will give the best performance, anything lower do not
# expect fast chats, embeddings, or other functionality.

# Exported from Render on 2024-03-24T00:18:18Z
services:
- type: web
  name: ANA-INEC
  runtime: image
  image:
    url: docker.io/mintplexlabs/anythingllm:render
  plan: standard
  envVars:
  - key: STORAGE_DIR
    sync: false
  - key: PORT
    sync: false
  region: oregon
  healthCheckPath: /api/ping
  domains:
  - bot.div-an-est-inv-crim.xyz
  - ana-inec.sytes.net
  disk:
    name: AnythingLLM Storage
    mountPath: /storage
    sizeGB: 10
  autoDeploy: false
version: "1"
